### ISSUE TITLE
Fails to work with HA Core version 2022.40

### ISSUE THREAD

**Issue by steinaaj** [dingusdk/ha-dukaone#4]
I get the following failure from the log, after updating:

Unable to prepare setup for platform dukaone.fan: Platform not found (cannot import name 'SPEED_HIGH' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).

**Comment by rogerrb** [comment]
I have the same problem, and find that the HIGH, LOW and MEDIUM speed settings are depreceated after Home Assistant 2022.3 according to the fan class documentation (https://github.com/home-assistant/core/commit/723dcbafca45267bf0d57016fc82e61beb69969f)

**Comment by dingusdk** [comment]
Updated version 1.0.6 should fix this

**Comment by rogerrb** [comment]
It works perfect. Thank you for the quick response. :)

**Comment by larsbloch** [comment]
Hey. Some simle syntax examples would be much apreciated.

I have some trouble with the new set_preset_mode
sequence:
  - service: fan.set_preset_mode
    data:
      speed: high
    target:
      entity_id: fan.airvent_washroom
      
     How do i supply the correct speed
     
     "call service script/1649512423018. extra keys not allowed @ data['speed']"

**Comment by dingusdk** [comment]
speed should be changed to preset_mode
You can see it [here in the fan documentation](https://www.home-assistant.io/integrations/fan/#service-fanset_preset_mode)
